// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzuSCtIeZUVszK4G5w82l9o_jH6zLPO0',
    appId: '1:147945602823:web:9abfa5925a52d8f7630fa2',
    messagingSenderId: '147945602823',
    projectId: 'cinemaskope-42c3e',
    authDomain: 'cinemaskope-42c3e.firebaseapp.com',
    storageBucket: 'cinemaskope-42c3e.firebasestorage.app',
    measurementId: 'G-FHDXJ8D7W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqpZfaIJzfu7MhAAk32jItK7YwcCfAxWg',
    appId: '1:147945602823:android:1b23ae08dc70233a630fa2',
    messagingSenderId: '147945602823',
    projectId: 'cinemaskope-42c3e',
    storageBucket: 'cinemaskope-42c3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV6SlGn6UXtF_6au-9rZQX5oAZseiB26c',
    appId: '1:147945602823:ios:9cf8e7aa20685da2630fa2',
    messagingSenderId: '147945602823',
    projectId: 'cinemaskope-42c3e',
    storageBucket: 'cinemaskope-42c3e.firebasestorage.app',
    iosBundleId: 'com.example.chapter9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV6SlGn6UXtF_6au-9rZQX5oAZseiB26c',
    appId: '1:147945602823:ios:9cf8e7aa20685da2630fa2',
    messagingSenderId: '147945602823',
    projectId: 'cinemaskope-42c3e',
    storageBucket: 'cinemaskope-42c3e.firebasestorage.app',
    iosBundleId: 'com.example.chapter9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTzuSCtIeZUVszK4G5w82l9o_jH6zLPO0',
    appId: '1:147945602823:web:c0e8db13657c30f7630fa2',
    messagingSenderId: '147945602823',
    projectId: 'cinemaskope-42c3e',
    authDomain: 'cinemaskope-42c3e.firebaseapp.com',
    storageBucket: 'cinemaskope-42c3e.firebasestorage.app',
    measurementId: 'G-N98JQSG1T6',
  );
}
